{
  "id": "GHSA-6429-3g3w-6mw5",
  "summary": "Uncaught Exception in bignum",
  "details": "All versions of the npm package bignum are vulnerable to Denial of Service (DoS) due to a type-check exception in V8. When verifying the type of the second argument to the .powm function, V8 will crash regardless of Node try/catch blocks.",
  "aliases": [
    "CVE-2022-25324"
  ],
  "modified": "2022-05-24T20:58:02Z",
  "published": "2022-05-07T00:00:31Z",
  "database_specific": {
    "nvd_published_at": "2022-05-06T20:15:00Z",
    "github_reviewed_at": "2022-05-24T20:58:02Z",
    "severity": "HIGH",
    "github_reviewed": true,
    "cwe_ids": [
      "CWE-248"
    ]
  },
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-25324"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/justmoon/node-bignum"
    },
    {
      "type": "WEB",
      "url": "https://github.com/justmoon/node-bignum/blob/ef2e02533e598d6df8421000033c4753cde89ee2/index.js#L111"
    },
    {
      "type": "WEB",
      "url": "https://snyk.io/vuln/SNYK-JS-BIGNUM-2388581"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "bignum",
        "ecosystem": "npm",
        "purl": "pkg:npm/bignum"
      },
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "0"
            },
            {
              "last_affected": "0.13.1"
            }
          ]
        }
      ],
      "database_specific": {
        "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2022/05/GHSA-6429-3g3w-6mw5/GHSA-6429-3g3w-6mw5.json"
      }
    }
  ],
  "schema_version": "1.6.0",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    }
  ]
}